version: '3.9'
name: take5_algo1

services:
  python_analytics:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: take5_algo1_python
    ports:
      - "8100:8080"
    networks:
      - kafka_broker_kafka-net
    environment:
      - RUN_MODE=docker
      - KAFKA_GROUP_ID=take5_algo1_group
      - LOG_LEVEL=INFO
    restart: unless-stopped

networks:
  kafka_broker_kafka-net:
    external: true
